import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { connection } from "next/server";
import { getDb } from "@/lib/mongodb";
import { spectacles as fixtures } from "@/lib/spectacles";
import type { SpectacleDocument } from "@/lib/spectacle-admin";

export const metadata: Metadata = { title: "Spectacles", description: "Les spectacles proposés aux professionnels par Piccolo Teatro." };
export default async function SpectaclesPage() { await connection(); const saved = await (await getDb()).collection<SpectacleDocument>("spectacles").find({ status: "published" }).sort({ createdAt: -1 }).toArray(); const items = [...fixtures.map(x => ({ slug: x.slug, title: x.title, season: x.season, description: x.description, image: x.image })), ...saved.filter(x => !fixtures.some(f => f.slug === x.slug)).map(x => ({ slug: x.slug, title: x.title, season: x.season, description: x.description, image: x.image }))]; return <main className="min-h-dvh bg-[#050505] pb-[clamp(90px,12vh,150px)] pt-[clamp(150px,19vh,220px)]"><div className="site-container"><p className="section-kicker">Diffusion professionnelle</p><h1 className="mt-5 font-display text-[clamp(54px,9vw,150px)] leading-[.9]">Nos <em className="font-normal text-accent">spectacles</em></h1><p className="mb-[clamp(50px,8vh,90px)] mt-8 max-w-[52ch] text-[clamp(16px,1.2vw,19px)] leading-8 text-muted">Des créations pensées pour voyager, rencontrer les équipes culturelles et dialoguer avec les territoires.</p><div className="grid gap-[clamp(24px,3vw,48px)] md:grid-cols-2 xl:grid-cols-3">{items.map((item, index) => <Link href={`/spectacles/${item.slug}`} key={item.slug} data-reveal className="group"><div className="relative aspect-[4/3] overflow-hidden border border-foreground/10 bg-surface"><Image src={item.image || "https://images.unsplash.com/photo-1507924538820-ede94a04019d?w=900&h=1200&fit=crop&q=80"} alt={item.title} fill sizes="(max-width:768px) 100vw,33vw" className="object-cover brightness-50 transition duration-1000 group-hover:scale-105 group-hover:brightness-75" /><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent" /><span className="absolute right-5 top-5 font-mono text-[10px] tracking-[.16em] text-accent">0{index + 1}</span></div><p className="mt-5 text-[10px] uppercase tracking-[.22em] text-accent">{item.season}</p><h2 className="mt-2 font-display text-[clamp(28px,2.6vw,42px)] leading-none">{item.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-muted">{item.description}</p><span className="mt-5 inline-flex items-center gap-3 text-[11px] uppercase tracking-[.18em]">Voir le spectacle <i className="h-px w-7 bg-accent" /></span></Link>)}{!items.length ? <p className="text-muted">Aucun spectacle publié.</p> : null}</div></div></main>; }
