import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { connection } from "next/server";
import { getDb } from "@/lib/mongodb";
import type { EventDocument } from "@/lib/events";

export const metadata: Metadata = { title: "Événements", description: "La programmation publique de Piccolo Teatro." };
export default async function EventsPage() { await connection(); const items = await (await getDb()).collection<EventDocument>("events").find({ status: "published" }).sort({ startsAt: 1 }).toArray(); return <main className="min-h-dvh bg-[#050505] pb-[clamp(90px,12vh,150px)] pt-[clamp(150px,19vh,220px)]"><div className="site-container"><p className="section-kicker">Agenda</p><h1 className="mt-5 font-display text-[clamp(54px,9vw,150px)] leading-[.9]">Les <em className="font-normal text-accent">événements</em></h1><p className="mb-[clamp(50px,8vh,90px)] mt-8 max-w-[50ch] text-[clamp(16px,1.2vw,19px)] leading-8 text-muted">Toutes les dates, rencontres et soirées du Piccolo Teatro.</p><div className="border-b border-foreground/10">{items.map(item => { const date = new Date(item.startsAt); return <Link href={`/evenements/${item.slug}`} key={item.slug} data-reveal className="group grid items-center gap-7 border-t border-foreground/10 py-[clamp(28px,3.5vw,48px)] transition hover:pl-3 md:grid-cols-[.55fr_1.2fr_1fr]"><div><span className="font-display text-[clamp(64px,7vw,110px)] leading-none">{String(date.getDate()).padStart(2, "0")}</span><p className="text-[10px] uppercase tracking-[.2em] text-accent">{new Intl.DateTimeFormat("fr-FR", { month: "long" }).format(date)} · {item.category}</p></div><div><h2 className="font-display text-[clamp(28px,3vw,46px)] leading-none">{item.title}</h2><p className="mt-4 flex gap-5 text-sm text-muted"><span>{item.venue}</span><span>{new Intl.DateTimeFormat("fr-FR", { hour: "2-digit", minute: "2-digit" }).format(date)}</span></p></div><div className="relative aspect-[16/9] overflow-hidden"><Image src={item.heroImage || item.contentImage || "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=1200&h=700&fit=crop&q=80"} alt={item.title} fill sizes="(max-width:768px) 100vw,35vw" className="object-cover brightness-60 transition duration-700 group-hover:scale-105 group-hover:brightness-85" /></div></Link>; })}{!items.length ? <p className="border-t border-foreground/10 py-20 text-center font-display text-3xl text-muted">Aucun événement publié.</p> : null}</div></div></main>; }
