import type { Metadata } from "next";
import Image from "next/image";
import { ActivityCta, ActivityHero, ActivityKicker, Facts } from "@/components/site/home/activity-ui";

export const metadata: Metadata = { title: "Diffusion artistique" };
const forms = [
  ["01", "Spectacles", "Des créations portées en salle, dans leur forme aboutie.", "photo-1503095396549-807759245b35"], ["02", "Représentations", "Séries et tournées, pour installer une œuvre dans la durée.", "photo-1507924538820-ede94a04019d"],
  ["03", "Expositions", "Donner à voir le travail plastique et les traces du processus.", "photo-1518998053901-5348d3961a04"], ["04", "Projections", "Captations, films et formats écran présentés au public.", "photo-1489599849927-2ee91cede3ba"],
  ["05", "Rencontres", "Échanges avec les artistes, avant ou après la représentation.", "photo-1517457373958-b7bdd4587205"], ["06", "Événements culturels", "Temps forts, festivals et soirées qui rassemblent les publics.", "photo-1470229722913-7c0e2dbbafd3"],
] as const;
const benefits = [["01", "Valoriser", "Mettre en lumière les artistes et leurs œuvres, avec les moyens et le cadre qu’elles méritent."], ["02", "Rendre visible", "Développer la visibilité des projets auprès des lieux, des partenaires et de la presse."], ["03", "Faire se rencontrer", "Créer les conditions de la rencontre entre la création artistique et le public."]] as const;
const facts = [{ label: "Formats", value: "Salle, exposition, écran, rencontre" }, { label: "Pour qui", value: "Artistes et compagnies accompagnés" }, { label: "Portée", value: "Lieux, partenaires et publics" }, { label: "Finalité", value: "La rencontre avec le public" }];
const words = ["Spectacles", "Représentations", "Expositions", "Projections", "Rencontres", "Événements culturels"];

export default function DiffusionPage() {
  return <>
    <ActivityHero index="02" title="Diffusion" description="L’ensemble des actions qui permettent de faire connaître, présenter et rendre accessibles les créations artistiques au public." primary="Diffuser un projet" anchor={{ label: "Les formes de diffusion", href: "#formes" }}>{[18,34,52,71,86].map((top,index) => <span key={top} className="absolute left-0 w-[46%] bg-gradient-to-r from-transparent via-accent/40 to-transparent [animation:band-sweep_linear_infinite]" style={{ top:`${top}%`, height:index%2 ? 1:2, animationDuration:`${11+index*1.5}s`, animationDelay:`${index*.8}s` }} />)}<div className="absolute inset-0 bg-[radial-gradient(115%_85%_at_20%_55%,rgba(239,47,41,.1),transparent_60%),radial-gradient(120%_90%_at_50%_100%,transparent_45%,#050505_100%)]" /></ActivityHero>
    <div className="overflow-hidden border-y border-border py-[18px]"><div className="activity-ticker flex w-max">{[...words,...words].map((word,index) => <span key={`${word}-${index}`} className={`flex items-center gap-[clamp(20px,3vw,44px)] whitespace-nowrap pr-[clamp(20px,3vw,44px)] font-display text-[clamp(17px,1.6vw,25px)] ${index%2 ? "text-foreground/55":"text-foreground"}`}>{word}<i className="h-[5px] w-[5px] rounded-full bg-accent" /></span>)}</div></div>
    <section id="formes" className="scroll-mt-28 py-[clamp(70px,11vh,130px)]"><div className="site-container"><ActivityKicker>Les formes de diffusion</ActivityKicker><h2 data-reveal className="section-title mb-[clamp(40px,6vh,68px)] max-w-[26ch] text-[clamp(30px,4.2vw,60px)]">Six manières de porter une œuvre <em>devant un public</em></h2><div className="grid grid-cols-[repeat(auto-fit,minmax(220px,1fr))] gap-[clamp(14px,1.8vw,26px)]">{forms.map(([num,title,desc,img]) => <article key={num} data-reveal className="group relative aspect-[3/4] overflow-hidden border border-foreground/15 transition duration-500 hover:-translate-y-2"><Image src={`https://images.unsplash.com/${img}?w=700&h=930&fit=crop&q=75`} alt="" fill sizes="(max-width:768px)100vw,25vw" className="object-cover grayscale brightness-[.42] transition duration-700 group-hover:scale-105 group-hover:grayscale-0 group-hover:brightness-75" /><div className="absolute inset-0 bg-gradient-to-t from-background via-background/25 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-[clamp(16px,1.8vw,24px)]"><span className="font-mono text-[10px] tracking-[.2em] text-accent">{num}</span><h3 className="mt-2.5 font-display text-[clamp(20px,1.8vw,28px)]">{title}</h3><p className="mt-0 max-h-0 overflow-hidden text-[13.5px] leading-[1.7] text-muted opacity-0 transition-all duration-500 group-hover:mt-3 group-hover:max-h-28 group-hover:opacity-100">{desc}</p></div></article>)}</div></div></section>
    <section className="border-t border-border bg-surface py-[clamp(70px,11vh,130px)]"><div className="site-container grid grid-cols-[repeat(auto-fit,minmax(300px,1fr))] items-center gap-[clamp(36px,5vw,84px)]"><div><ActivityKicker>Notre rôle</ActivityKicker><h2 data-reveal className="section-title text-[clamp(30px,4.2vw,60px)]">Faire circuler les œuvres, <em className="text-accent">élargir le cercle</em></h2><p data-reveal className="mt-6 max-w-[54ch] text-[clamp(15.5px,1.15vw,18px)] leading-[1.85] text-muted">Le centre accompagne les artistes dans la diffusion de leurs projets à travers des spectacles, représentations, expositions, projections, rencontres et événements culturels.</p><p data-reveal className="mt-[22px] max-w-[54ch] italic leading-[1.85]">Valoriser les artistes et leurs œuvres, développer leur visibilité, et favoriser la rencontre entre la création et le public.</p></div><div data-reveal className="relative aspect-square"><span className="absolute left-[12%] top-1/2 h-3 w-3 -translate-y-1/2 rounded-full bg-accent shadow-[0_0_24px_rgba(239,47,41,.7)]" />{[58,76,94,112].map((size,index)=><span key={size} className="absolute left-[12%] top-1/2 aspect-square -translate-y-1/2 rounded-full border border-accent/30 [animation:arc-out_6s_ease-out_infinite]" style={{ width:`${size}%`, animationDelay:`${index*1.5}s` }} />)}<div className="absolute right-[2%] top-1/2 -translate-y-1/2 text-right"><p className="font-mono text-[10.5px] uppercase tracking-[.2em] text-muted">Au bout de la portée</p><p className="mt-2 font-display text-[clamp(26px,3vw,46px)] italic">le public</p></div></div></div></section>
    <section className="py-[clamp(70px,11vh,130px)]"><div className="site-container"><div className="mb-10"><ActivityKicker>Ce que la diffusion apporte</ActivityKicker></div>{benefits.map(([num,title,desc]) => <article key={num} data-reveal className="group grid grid-cols-[repeat(auto-fit,minmax(240px,1fr))] items-baseline gap-[clamp(14px,2.4vw,44px)] border-t border-border py-[clamp(26px,3.4vw,44px)] transition-[padding] hover:pl-4"><div className="flex items-baseline gap-4"><span className="font-mono text-[11px] text-accent">{num}</span><h3 className="font-display text-[clamp(24px,3vw,46px)]">{title}</h3></div><p className="max-w-[54ch] leading-[1.8] text-muted">{desc}</p></article>)}</div></section>
    <Facts items={facts} />
    <ActivityCta title="Votre œuvre mérite d’être" accent="vue" text="Parlons de votre projet et des lieux, formats et publics qui lui conviennent." primary="Nous contacter" secondary={{ label: "Voir les spectacles", href: "/#spectacles" }} />
  </>;
}
