import type { Metadata } from "next";
import Link from "next/link";
import { getSession } from "@/lib/auth";

export const metadata: Metadata = { title: "Tableau de bord" };

const stats = [{ label: "Spectacles", value: "01", note: "1 en tournée" }, { label: "Ateliers", value: "03", note: "Tous actifs" }, { label: "Activités", value: "03", note: "Programmes publiés" }, { label: "Candidatures", value: "00", note: "Aucune en attente" }];

export default async function DashboardPage() {
  const user = await getSession();
  return <><div className="mb-[clamp(30px,5vw,52px)] flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-[10px] uppercase tracking-[.24em] text-[#EF2F29]">Vue d’ensemble</p><h1 className="font-display text-[clamp(38px,5vw,64px)] leading-none">Tableau de bord</h1><p className="mt-4 text-sm text-[#77716B]">Bienvenue, {user?.name}. Voici l’activité de votre espace.</p></div><p className="text-[11px] uppercase tracking-[.16em] text-[#8B857F]">Saison 2026 — 2027</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat, index) => <article key={stat.label} className="group border border-black/[.09] bg-[#FBFAF7] p-6 transition hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(20,15,10,.08)]"><div className="mb-10 flex items-start justify-between"><span className="text-[11px] uppercase tracking-[.18em] text-[#77716B]">{stat.label}</span><span className="font-mono text-[10px] text-[#EF2F29]">0{index + 1}</span></div><p className="font-display text-5xl">{stat.value}</p><p className="mt-2 text-xs text-[#908A84]">{stat.note}</p></article>)}</section><section className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><article className="min-h-[300px] border border-black/[.09] bg-[#FBFAF7] p-[clamp(24px,3vw,38px)]"><p className="text-[10px] uppercase tracking-[.22em] text-[#EF2F29]">Activité récente</p><div className="grid min-h-[220px] place-items-center text-center"><div><p className="font-display text-2xl text-[#4D4843]">Tout est calme pour le moment</p><p className="mt-2 text-sm text-[#918B85]">Les prochaines actions apparaîtront ici.</p></div></div></article><article className="bg-[#111] p-[clamp(24px,3vw,38px)] text-[#F3EFE9]"><p className="text-[10px] uppercase tracking-[.22em] text-[#EF2F29]">Accès rapide</p><h2 className="mt-5 font-display text-3xl">Votre contenu, simplement.</h2><p className="mt-3 text-sm leading-6 text-[#96918C]">Utilisez le menu latéral pour administrer les pages du site.</p><Link href="/" target="_blank" className="mt-9 inline-flex border border-white/20 px-5 py-3 text-[10px] uppercase tracking-[.18em] transition hover:border-[#EF2F29] hover:text-[#EF2F29]">Voir le site ↗</Link></article></section></>;
}
