import type { CSSProperties, ReactNode } from "react";
import Link from "next/link";

export function ActivityKicker({ children }: { children: ReactNode }) {
  return <p className="section-kicker">{children}</p>;
}

export function ActivityHero({ index, title, description, primary, anchor, children, centered = false }: { index: string; title: string; description: string; primary: string; anchor: { label: string; href: string }; children?: ReactNode; centered?: boolean }) {
  return <section className={`relative flex min-h-[94svh] overflow-hidden pb-[clamp(44px,7vh,80px)] pt-[clamp(126px,18vh,196px)] ${centered ? "items-center text-center" : "items-end"}`}>{children}<div className={`site-container relative z-[3] ${centered ? "max-w-[1100px]" : ""}`}><Link href="/#activites" className="mb-[26px] inline-flex text-[11.5px] uppercase tracking-[.18em] text-muted hover:text-accent">← Retour aux activités</Link><div className={`mb-[18px] flex flex-wrap items-center gap-3.5 ${centered ? "justify-center" : ""}`}><span className="font-mono text-[11.5px] tracking-[.2em] text-accent">ACTE IV · {index}</span><span className="h-px w-[46px] bg-accent" /><span className="text-[11px] uppercase tracking-[.28em] text-muted">{index === "03" ? "Programme d’accompagnement" : "Activité — Sur les planches"}</span></div><h1 className="font-display text-[clamp(46px,9.4vw,168px)] font-normal leading-[.92] tracking-[-.03em]">{title}<br /><em className="font-normal text-accent">artistique</em></h1><p data-reveal className={`mt-[clamp(30px,4.4vh,48px)] max-w-[56ch] text-[clamp(16px,1.2vw,19px)] leading-[1.8] text-muted ${centered ? "mx-auto" : ""}`}>{description}</p><div data-reveal style={{ "--reveal-delay": "140ms" } as CSSProperties} className={`mt-[clamp(30px,4vh,44px)] flex flex-wrap gap-3.5 ${centered ? "justify-center" : ""}`}><a href="https://www.facebook.com/piccoloteatrodibizerta/?locale=fr_FR" target="_blank" rel="noopener noreferrer" className="bg-accent px-7 py-4 text-xs uppercase tracking-[.16em] text-accent-foreground transition hover:-translate-y-[3px] hover:shadow-[0_18px_44px_rgba(239,47,41,.32)]">{primary}</a><Link href={anchor.href} className="border border-foreground/25 px-7 py-4 text-xs uppercase tracking-[.16em] transition hover:-translate-y-[3px] hover:border-foreground">{anchor.label}</Link></div></div></section>;
}

export function Facts({ items }: { items: readonly { label: string; value: string }[] }) {
  return <section className="border-y border-border bg-surface py-[clamp(44px,7vh,80px)]"><div className="site-container grid grid-cols-[repeat(auto-fit,minmax(200px,1fr))] gap-[clamp(26px,4vw,60px)]">{items.map((item) => <div key={item.label} data-reveal><p className="mb-3.5 font-mono text-[11px] uppercase tracking-[.18em] text-accent">{item.label}</p><p className="font-display text-[clamp(19px,1.7vw,27px)] leading-[1.3]">{item.value}</p></div>)}</div></section>;
}

export function ActivityCta({ title, accent, text, primary, secondary }: { title: string; accent: string; text: string; primary: string; secondary: { label: string; href: string } }) {
  return <section className="relative overflow-hidden py-[clamp(80px,12vh,150px)] text-center"><div className="absolute inset-0 bg-[radial-gradient(80%_60%_at_50%_100%,rgba(239,47,41,.16),transparent_65%)]" /><div className="relative mx-auto max-w-[900px] px-[clamp(18px,4vw,60px)]"><h2 data-reveal className="mb-[22px] font-display text-[clamp(32px,5.2vw,78px)] leading-[1.03] tracking-[-.02em]">{title} <em className="font-normal text-accent">{accent}</em></h2><p data-reveal className="mx-auto mb-[34px] max-w-[46ch] text-[clamp(15px,1.1vw,17px)] leading-[1.8] text-muted">{text}</p><div data-reveal className="flex flex-wrap justify-center gap-3.5"><a href="https://www.facebook.com/piccoloteatrodibizerta/?locale=fr_FR" target="_blank" rel="noopener noreferrer" className="bg-accent px-8 py-[17px] text-xs uppercase tracking-[.16em] text-accent-foreground transition hover:-translate-y-[3px]">{primary}</a><Link href={secondary.href} className="border border-foreground/25 px-8 py-[17px] text-xs uppercase tracking-[.16em] transition hover:-translate-y-[3px] hover:border-foreground">{secondary.label}</Link></div></div></section>;
}
