import type { Metadata } from "next";
import Image from "next/image";
import { ActivityCta, ActivityHero, ActivityKicker, Facts } from "@/components/site/home/activity-ui";

export const metadata: Metadata = { title: "Incubation artistique" };
const pillars = [["01", "Artistique", "Regards extérieurs, conseil dramaturgique et retours de plateau pour affiner l’intention."], ["02", "Technique", "Lumière, son, scénographie : traduire une idée en moyens concrets et réalisables."], ["03", "Administratif", "Statuts, dossiers, démarches et suivi — le cadre qui permet au projet d’exister."]] as const;
const skills = [["Gestion de projet", "Cadrer · planifier", "88%"], ["Communication", "Dire · diffuser", "76%"], ["Production culturelle", "Financer · monter", "82%"]] as const;
const spaces = [["Échange", "Un collectif de porteurs de projets qui avancent côte à côte.", "photo-1517457373958-b7bdd4587205"], ["Conseil", "Des rendez-vous réguliers avec l’équipe et des intervenants du secteur.", "photo-1522071820081-009f0129c71c"], ["Expérimentation", "Le droit d’essayer, de rater et de recommencer avant de montrer.", "photo-1503095396549-807759245b35"]] as const;
const facts = [{ label: "Pour qui", value: "Jeunes artistes et porteurs de projets" }, { label: "Accompagnement", value: "Artistique, technique, administratif" }, { label: "On développe", value: "Gestion, communication, production" }, { label: "Finalité", value: "Transformer une idée en projet" }];

export default function IncubationPage() {
  return <>
    <ActivityHero index="03" title="Incubation" centered description="Pour les jeunes artistes, créateurs et porteurs de projets culturels qui veulent développer et concrétiser leurs idées." primary="Candidater" anchor={{ label: "Le programme", href: "#programme" }}><div className="absolute left-1/2 top-[52%] aspect-square w-[min(880px,116vw)] -translate-x-1/2 -translate-y-1/2"><span className="chamber-breathe absolute left-1/2 top-1/2 h-full w-full rounded-full bg-[radial-gradient(circle,rgba(239,47,41,.30)_0%,rgba(239,47,41,.07)_42%,transparent_68%)] blur-[30px]" />{[0,2.3,4.6].map((delay,index)=><span key={delay} className={`absolute left-1/2 top-1/2 h-[62%] w-[62%] rounded-full border ${index===1?"border-accent/30":"border-foreground/15"} [animation:ring-pulse_7s_ease-out_infinite]`} style={{ animationDelay:`${delay}s` }} />)}</div>{[14,27,41,54,67,79,88].map((left,index)=><span key={left} className="absolute bottom-[12%] h-[3px] w-[3px] rounded-full bg-accent opacity-0 [animation:mote-float_linear_infinite]" style={{ left:`${left}%`, animationDuration:`${8+(index%5)}s`, animationDelay:`${index*.8}s` }} />)}</ActivityHero>
    <section className="border-t border-border py-[clamp(60px,10vh,120px)]"><div className="mx-auto grid max-w-[1200px] grid-cols-[repeat(auto-fit,minmax(220px,1fr))] items-center gap-[clamp(24px,4vw,56px)] px-[clamp(18px,4vw,60px)]"><div data-reveal className="border border-dashed border-foreground/25 px-5 py-[clamp(30px,4vw,50px)] text-center"><p className="font-mono text-[10.5px] uppercase tracking-[.2em] text-muted">Au départ</p><p className="mt-4 font-display text-[clamp(30px,3.6vw,54px)] italic">une idée</p></div><div data-reveal className="text-center"><div className="h-px bg-gradient-to-r from-transparent via-accent to-transparent" /><p className="my-3.5 font-mono text-[10.5px] uppercase tracking-[.2em] text-accent">Incubation</p><div className="h-px bg-gradient-to-r from-transparent via-accent to-transparent" /></div><div data-reveal className="border border-accent bg-accent/10 px-5 py-[clamp(30px,4vw,50px)] text-center"><p className="font-mono text-[10.5px] uppercase tracking-[.2em] text-muted">À l’arrivée</p><p className="mt-4 font-display text-[clamp(30px,3.6vw,54px)]">un projet</p></div></div></section>
    <section id="programme" className="scroll-mt-28 border-t border-border bg-surface py-[clamp(70px,11vh,130px)]"><div className="site-container"><ActivityKicker>Trois accompagnements</ActivityKicker><h2 data-reveal className="section-title mb-[clamp(40px,6vh,68px)] max-w-[24ch] text-[clamp(30px,4.2vw,60px)]">Un soutien <em>artistique</em>, technique et administratif</h2><div className="grid grid-cols-[repeat(auto-fit,minmax(270px,1fr))] gap-[clamp(16px,2vw,28px)]">{pillars.map(([num,title,desc])=><article key={num} data-reveal className="group relative overflow-hidden border border-foreground/15 px-[clamp(24px,2.6vw,36px)] py-[clamp(30px,3.4vw,48px)] transition duration-500 hover:-translate-y-1.5 hover:border-accent"><span className="absolute left-1/2 top-0 aspect-[2/1] w-[120%] -translate-x-1/2 -translate-y-[60%] rounded-full bg-[radial-gradient(circle,rgba(239,47,41,.22),transparent_65%)] opacity-0 transition-opacity group-hover:opacity-100" /><div className="relative"><span className="font-mono text-[10.5px] tracking-[.2em] text-accent">{num}</span><h3 className="mb-3.5 mt-[22px] font-display text-[clamp(24px,2.2vw,36px)]">{title}</h3><p className="text-[14.5px] leading-[1.8] text-muted">{desc}</p></div></article>)}</div></div></section>
    <section className="py-[clamp(70px,11vh,130px)]"><div className="site-container grid grid-cols-[repeat(auto-fit,minmax(300px,1fr))] items-center gap-[clamp(36px,5vw,84px)]"><div><ActivityKicker>Compétences développées</ActivityKicker><h2 data-reveal className="section-title text-[clamp(30px,4vw,56px)]">Apprendre à porter son projet <em className="text-accent">jusqu’au bout</em></h2><p data-reveal className="mt-[22px] max-w-[50ch] text-[clamp(15.5px,1.15vw,18px)] leading-[1.85] text-muted">Au-delà de l’artistique, l’incubation forme aux savoir-faire qui font tenir une création dans le réel.</p></div><div className="flex flex-col gap-[clamp(22px,3vh,34px)]">{skills.map(([title,tag,width])=><div key={title} data-reveal><div className="mb-3 flex items-baseline justify-between gap-4"><span className="font-display text-[clamp(19px,1.7vw,27px)]">{title}</span><span className="font-mono text-[10.5px] uppercase tracking-[.16em] text-muted">{tag}</span></div><div className="h-0.5 bg-foreground/15"><span className="block h-full bg-accent transition-[width] duration-1000" style={{ width }} /></div></div>)}</div></div></section>
    <section className="border-t border-border py-[clamp(70px,11vh,130px)]"><div className="site-container"><div className="mb-11"><ActivityKicker>Un espace de</ActivityKicker></div><div className="grid grid-cols-[repeat(auto-fit,minmax(260px,1fr))] gap-[clamp(20px,2.6vw,40px)]">{spaces.map(([title,desc,img])=><article key={title} data-reveal><div className="relative mb-[22px] aspect-[5/4] overflow-hidden border border-foreground/15"><Image src={`https://images.unsplash.com/${img}?w=900&h=720&fit=crop&q=75`} alt="" fill sizes="33vw" className="object-cover grayscale-[.8] brightness-[.55] transition duration-700 hover:scale-105 hover:grayscale-0" /><div className="absolute inset-0 bg-[radial-gradient(70%_70%_at_50%_60%,rgba(239,47,41,.18),transparent_70%)]" /></div><h3 className="mb-2.5 font-display text-[clamp(23px,2.1vw,34px)]">{title}</h3><p className="max-w-[34ch] text-[14.5px] leading-[1.75] text-muted">{desc}</p></article>)}</div></div></section>
    <Facts items={facts} />
    <ActivityCta title="Vous avez une" accent="idée ?" text="Présentez-la nous, même à l’état d’esquisse. L’incubation commence par une conversation." primary="Candidater" secondary={{ label: "Production artistique", href: "/activites/production" }} />
  </>;
}
