import type { Metadata } from "next";
import Image from "next/image";
import { ActivityCta, ActivityHero, ActivityKicker, Facts } from "@/components/site/home/activity-ui";

export const metadata: Metadata = { title: "Production artistique" };
const facts = [{ label: "Domaine", value: "Théâtre & spectacle vivant" }, { label: "Pour qui", value: "Artistes et porteurs de projets" }, { label: "Étapes", value: "De la conception à la présentation" }, { label: "Objectif", value: "Faire émerger de nouvelles créations" }];
const phases = [
  ["01", "Conception", "Note d’intention, dramaturgie, faisabilité : on clarifie le projet et ce qu’il demande avant d’engager le plateau."],
  ["02", "Réalisation", "Budget, calendrier, distribution, partenaires — le projet devient une production structurée et tenable."],
  ["03", "Répétitions", "Un plateau disponible dans la durée, pour chercher, se tromper et laisser la pièce trouver sa forme."],
  ["04", "Mise en scène", "Direction d’acteurs, scénographie, lumière et son : l’écriture scénique se fixe."],
  ["05", "Présentation", "Sorties de résidence, première et rencontre avec le public — le moment où l’œuvre existe vraiment."],
] as const;
const means = [
  ["01", "Plateau & résidence", "Un lieu de répétition équipé, mis à disposition sur des créneaux dédiés."], ["02", "Accompagnement artistique", "Regards extérieurs, retours de plateau et conseil dramaturgique."],
  ["03", "Production & administration", "Structuration du budget, montage du dossier, suivi des démarches."], ["04", "Technique & scénographie", "Appui lumière, son et construction pour concrétiser les intentions."],
  ["05", "Réseau & partenaires", "Mise en relation avec les lieux, coproducteurs et programmateurs."], ["06", "Rencontre du public", "Sorties de résidence, avant-premières et temps d’échange."],
] as const;

export default function ProductionPage() {
  return <>
    <ActivityHero index="01" title="Production" description="Un espace dédié à la création et à la production de projets artistiques, dans le domaine du théâtre et du spectacle vivant." primary="Déposer un projet" anchor={{ label: "Le parcours", href: "#parcours" }}><div className="blueprint-grid absolute inset-0 opacity-50 bg-[repeating-linear-gradient(0deg,rgba(243,239,233,.055)_0_1px,transparent_1px_60px),repeating-linear-gradient(90deg,rgba(243,239,233,.055)_0_1px,transparent_1px_60px)]" /><div className="sweep-beam absolute -top-[30%] left-1/2 h-[120%] w-[min(1100px,120vw)] -translate-x-1/2 bg-[conic-gradient(from_170deg_at_50%_0%,transparent_0deg,rgba(239,47,41,.16)_12deg,rgba(243,239,233,.05)_22deg,transparent_34deg)] blur-2xl" /><div className="absolute inset-0 bg-[radial-gradient(120%_90%_at_50%_100%,transparent_40%,#050505_100%)]" /></ActivityHero>
    <Facts items={facts} />
    <section className="py-[clamp(70px,11vh,130px)]"><div className="site-container grid grid-cols-[repeat(auto-fit,minmax(320px,1fr))] items-center gap-[clamp(40px,6vw,96px)]"><div><ActivityKicker>Notre rôle</ActivityKicker><h2 data-reveal className="section-title text-[clamp(32px,4.4vw,66px)]">Accompagner les artistes à <em className="text-accent">chaque étape</em></h2><p data-reveal className="mt-7 max-w-[56ch] text-[clamp(15.5px,1.15vw,18px)] leading-[1.85] text-muted">Le centre accompagne les artistes et les porteurs de projets à différentes étapes de la création : de la conception à la réalisation, en passant par les répétitions, la mise en scène et la présentation au public.</p><p data-reveal className="mt-[22px] max-w-[56ch] text-[clamp(15.5px,1.15vw,18px)] italic leading-[1.85]">L’objectif : favoriser l’émergence de nouvelles créations et soutenir les artistes dans la concrétisation de leurs projets.</p></div><div data-reveal data-parallax="0.09" className="relative aspect-[4/5] overflow-hidden border border-foreground/15"><Image src="https://images.unsplash.com/photo-1503095396549-807759245b35?w=1000&h=1250&fit=crop&q=75" alt="Répétition sur un plateau" fill sizes="50vw" className="object-cover grayscale-[.75] brightness-[.62]" /><div className="absolute inset-0 bg-[radial-gradient(70%_60%_at_60%_35%,rgba(239,47,41,.22),transparent_70%)]" /></div></div></section>
    <section id="parcours" className="scroll-mt-28 border-t border-border bg-surface py-[clamp(70px,11vh,130px)]"><div className="site-container"><ActivityKicker>Le parcours d’une création</ActivityKicker><h2 data-reveal className="section-title mb-[clamp(44px,6vh,74px)] max-w-[22ch] text-[clamp(30px,4vw,58px)]">Cinq temps, de la première note d’intention au <em>salut final</em></h2><div className="relative ml-3 border-l border-foreground/15 pl-[clamp(34px,5vw,80px)]">{phases.map(([num,title,desc]) => <div key={num} data-reveal className="relative grid grid-cols-[repeat(auto-fit,minmax(240px,1fr))] gap-[clamp(16px,2.6vw,48px)] border-b border-border py-7 before:absolute before:-left-[calc(clamp(34px,5vw,80px)+5px)] before:top-9 before:h-[9px] before:w-[9px] before:rounded-full before:border before:border-foreground/50 before:bg-surface"><div className="flex items-baseline gap-4"><span className="font-mono text-[11.5px] text-accent">{num}</span><h3 className="font-display text-[clamp(24px,2.6vw,42px)]">{title}</h3></div><p className="text-[clamp(14.5px,1.05vw,16.5px)] leading-[1.8] text-muted">{desc}</p></div>)}</div></div></section>
    <section className="py-[clamp(70px,11vh,130px)]"><div className="site-container"><div className="mb-11"><ActivityKicker>Ce que nous mettons à disposition</ActivityKicker></div><div className="grid grid-cols-[repeat(auto-fit,minmax(250px,1fr))] gap-px bg-foreground/10">{means.map(([num,title,desc]) => <article key={num} data-reveal className="group relative overflow-hidden bg-background px-[clamp(22px,2.4vw,32px)] py-[clamp(28px,3.2vw,44px)]"><span className="absolute inset-y-0 left-0 w-0 bg-accent/10 transition-[width] duration-500 group-hover:w-full" /><div className="relative"><span className="font-mono text-[10.5px] tracking-[.2em] text-accent">{num}</span><h3 className="mb-2.5 mt-[18px] font-display text-[clamp(20px,1.8vw,29px)]">{title}</h3><p className="text-[14.5px] leading-[1.75] text-muted">{desc}</p></div></article>)}</div></div></section>
    <ActivityCta title="Vous portez un" accent="projet ?" text="Envoyez-nous une note d’intention : nous étudions chaque dossier et revenons vers vous pour un premier rendez-vous." primary="Nous contacter" secondary={{ label: "Autres activités", href: "/#activites" }} />
  </>;
}
