import { ObjectId } from "mongodb";
import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/admin-api";
import { getDb } from "@/lib/mongodb";
import { parseSpectacleInput, serializeSpectacle, type SpectacleDocument } from "@/lib/spectacle-admin";
import { cleanupImages, requestPayload, saveImage } from "@/lib/image-storage";
type Context = { params: Promise<{ id: string }> };
async function idOf(context: Context) { const { id } = await context.params; return ObjectId.isValid(id) ? new ObjectId(id) : null; }
export async function GET(_request: Request, context: Context) { const auth = await requireAdmin(); if ("response" in auth) return auth.response; const _id = await idOf(context); if (!_id) return NextResponse.json({ message: "Identifiant invalide." }, { status: 400 }); const item = await (await getDb()).collection<SpectacleDocument>("spectacles").findOne({ _id }); return item ? NextResponse.json({ spectacle: serializeSpectacle(item) }) : NextResponse.json({ message: "Spectacle introuvable." }, { status: 404 }); }
export async function PUT(request: Request, context: Context) { const auth = await requireAdmin(true); if ("response" in auth) return auth.response; const _id = await idOf(context); if (!_id) return NextResponse.json({ message: "Identifiant invalide." }, { status: 400 }); let payload; try { payload = await requestPayload(request); } catch { return NextResponse.json({ message: "Requête invalide." }, { status: 400 }); } const body = payload.body; const parsed = parseSpectacleInput(body); if ("error" in parsed) return NextResponse.json({ message: parsed.error }, { status: 400 }); const collection = (await getDb()).collection<SpectacleDocument>("spectacles"); if (await collection.findOne({ slug: parsed.data.slug, _id: { $ne: _id } })) return NextResponse.json({ message: "Ce slug est déjà utilisé." }, { status: 409 }); const previous = await collection.findOne({ _id }); if (!previous) return NextResponse.json({ message: "Spectacle introuvable." }, { status: 404 }); let image: string | null = null; try { image = await saveImage(payload.form?.get("imageFile") ?? null, "spectacles"); } catch (error) { return NextResponse.json({ message: (error as Error).message }, { status: 400 }); } let item; try { item = await collection.findOneAndUpdate({ _id }, { $set: { ...parsed.data, image: image || previous.image, updatedBy: new ObjectId(auth.session.id), updatedAt: new Date() } }, { returnDocument: "after" }); } catch (error) { await cleanupImages([image], "spectacles"); throw error; } if (item) await cleanupImages([image ? previous.image : null], "spectacles"); return item ? NextResponse.json({ spectacle: serializeSpectacle(item) }) : NextResponse.json({ message: "Spectacle introuvable." }, { status: 404 }); }
export async function DELETE(_request: Request, context: Context) { const auth = await requireAdmin(true); if ("response" in auth) return auth.response; const _id = await idOf(context); if (!_id) return NextResponse.json({ message: "Identifiant invalide." }, { status: 400 }); const result = await (await getDb()).collection<SpectacleDocument>("spectacles").findOneAndDelete({ _id }); if (!result) return NextResponse.json({ message: "Spectacle introuvable." }, { status: 404 }); await cleanupImages([result.image], "spectacles"); return NextResponse.json({ success: true }); }
