"use client";
import { useState, type FormEvent } from "react";
import type { EventStatus, EventProgramItem } from "@/lib/events";
import Link from "next/link";
import { Actions, Area, Check, Drawer, ErrorMessage, Field, FormSection, Select, localDate, ImageField } from "./form-ui";

export type EventItem = { _id: string; title: string; slug: string; status: "draft" | "published"; category: string; audience: string; ticketingOpen: boolean; startsAt: string; endsAt: string; venue: string; priceStudent: string; priceFull: string; heroImage: string; contentImage: string; introTitle: string; description: string; secondaryDescription: string; editionLabel: string; program: { time: string; title: string; performer: string; note: string }[] };
const empty = { title: "", slug: "", status: "draft", category: "Soirée", audience: "Tout public", ticketingOpen: false, startsAt: "", endsAt: "", venue: "", priceStudent: "", priceFull: "", heroImage: "", contentImage: "", introTitle: "", description: "", secondaryDescription: "", editionLabel: "", program: "" } as const;

export function EventsManager({ initialEvents }: { initialEvents: EventItem[] }) {
  const [items, setItems] = useState(initialEvents); const [editing, setEditing] = useState<EventItem | "new" | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const current = editing === "new" ? null : editing; const response = await fetch(current ? `/api/admin/evenements/${current._id}` : "/api/admin/evenements", { method: current ? "PUT" : "POST", body: form }); const result = await response.json(); setSaving(false); if (!response.ok) return setError(result.message || "Enregistrement impossible."); setItems(list => current ? list.map(item => item._id === current._id ? result.event : item) : [result.event, ...list]); setEditing(null); }
  async function remove(item: EventItem) { if (!confirm(`Supprimer définitivement « ${item.title} » ?`)) return; const response = await fetch(`/api/admin/evenements/${item._id}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) return setError(result.message || "Suppression impossible."); setItems(list => list.filter(value => value._id !== item._id)); }
  return <><Heading count={items.length} onCreate={() => setEditing("new")} />{error && !editing ? <ErrorMessage>{error}</ErrorMessage> : null}<AdminTable items={items} edit={setEditing} remove={remove} />{editing ? <EventForm item={editing === "new" ? null : editing} saving={saving} error={error} close={() => setEditing(null)} save={save} /> : null}</>;
}

function Heading({ count, onCreate }: { count: number; onCreate: () => void }) { return <div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-[10px] uppercase tracking-[.24em] text-[#EF2F29]">Programmation publique</p><h1 className="font-display text-[clamp(38px,5vw,64px)] leading-none">Événements</h1><p className="mt-4 text-sm text-[#77716B]">{count} élément{count !== 1 ? "s" : ""}</p></div><button onClick={onCreate} className="min-h-12 bg-[#EF2F29] px-6 text-[11px] font-medium uppercase tracking-[.17em] text-[#050505]">+ Créer un événement</button></div>; }
function AdminTable({ items, edit, remove }: { items: EventItem[]; edit: (item: EventItem) => void; remove: (item: EventItem) => void }) { return <div className="overflow-x-auto border border-black/[.09] bg-[#FBFAF7]"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-black/[.08] text-[10px] uppercase tracking-[.18em] text-[#837D77]"><th className="px-6 py-4">Événement</th><th className="px-4 py-4">Date</th><th className="px-4 py-4">Statut</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody>{items.map(item => <tr key={item._id} className="border-b border-black/[.06] even:bg-black/[.02] hover:bg-black/[.04] transition-colors"><td className="px-6 py-5"><p className="font-display text-xl">{item.title}</p><p className="font-mono text-[10px] text-[#96908A]">/{item.slug}</p></td><td className="px-4 py-5 text-sm">{new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.startsAt))}<small className="block text-[#96908A]">{item.venue}</small></td><td className="px-4 py-5"><span className={item.status === "published" ? "text-[#C5221D]" : "text-[#746E68]"}>{item.status === "published" ? "Publié" : "Brouillon"}</span></td><td className="px-6 py-5"><div className="flex justify-end gap-2">{item.status === "published" ? <Link href={`/evenements/${item.slug}`} target="_blank" className="flex items-center gap-1.5 bg-[#EF2F29] text-white px-3 py-1.5 text-[10px] uppercase tracking-[.1em] font-medium transition hover:bg-black"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="h-3 w-3"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg> Voir</Link> : null}<button onClick={() => edit(item)} className="flex items-center gap-1.5 border border-black/15 bg-white px-3 py-1.5 text-[10px] uppercase tracking-[.1em] font-medium transition hover:border-[#EF2F29] hover:text-[#EF2F29]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="h-3 w-3"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg> Modifier</button><button onClick={() => remove(item)} className="flex items-center gap-1.5 px-3 py-1.5 text-[10px] uppercase tracking-[.1em] font-medium text-red-600 transition hover:text-red-800"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="h-3 w-3"><path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg> Supprimer</button></div></td></tr>)}{!items.length ? <tr><td colSpan={4} className="py-20 text-center font-display text-2xl text-[#625D58]">Aucun événement</td></tr> : null}</tbody></table></div>; }
function EventForm({ item, saving, error, close, save }: { item: EventItem | null; saving: boolean; error: string; close: () => void; save: (event: FormEvent<HTMLFormElement>) => void }) { const v = item ? { ...item, startsAt: localDate(item.startsAt), endsAt: localDate(item.endsAt), program: item.program.map(x => `${x.time} | ${x.title} | ${x.performer} | ${x.note}`).join("\n") } : empty; return <Drawer title={item ? "Modifier l’événement" : "Nouvel événement"} onClose={close}><form onSubmit={save} className="space-y-10 p-[clamp(22px,4vw,44px)]">{error ? <ErrorMessage>{error}</ErrorMessage> : null}<FormSection title="Informations générales"><div className="grid gap-5 sm:grid-cols-2"><Field label="Titre *" name="title" defaultValue={v.title} required /><Select label="Statut" name="status" defaultValue={v.status} options={["draft|Brouillon", "published|Publié"]} /><Field label="Public" name="audience" defaultValue={v.audience} /><Field label="Lieu" name="venue" defaultValue={v.venue} /><Field label="Début *" name="startsAt" type="datetime-local" defaultValue={v.startsAt} required /><Field label="Fin *" name="endsAt" type="datetime-local" defaultValue={v.endsAt} required /></div><Check name="ticketingOpen" defaultChecked={v.ticketingOpen} label="Billetterie ouverte" /><div className="grid gap-5 sm:grid-cols-2"><Field label="Tarif étudiant" name="priceStudent" defaultValue={v.priceStudent} placeholder="ex: 9" /><Field label="Tarif complet" name="priceFull" defaultValue={v.priceFull} placeholder="ex: 18" /></div></FormSection><FormSection title="Page événement"><ImageField label="Image hero" name="heroImageFile" defaultValue={v.heroImage} hint="Ratio recommandé: 16:9" ratio="16/9" /><ImageField label="Image contenu" name="contentImageFile" defaultValue={v.contentImage} hint="Ratio recommandé: 4:5" ratio="4/5" /><Field label="Titre d’introduction" name="introTitle" defaultValue={v.introTitle} /><Area label="Présentation" name="description" defaultValue={v.description} /><Area label="Deuxième paragraphe" name="secondaryDescription" defaultValue={v.secondaryDescription} /><Field label="Légende / édition" name="editionLabel" defaultValue={v.editionLabel} /><Area label="Programme" hint="heure | titre | interprète | note" name="program" defaultValue={v.program} rows={6} /></FormSection><Actions saving={saving} onClose={close} /></form></Drawer>; }
